import { Loader } from "@/types";

// All loaders with categories
export const loaders: Loader[] = [
  // 001-025 (Basic Spinners & Shapes)
  { id: "001", name: "Classic Spinner", html: '<div class="loader-001"></div>', category: "spinners" },
  { id: "002", name: "Bouncing Dots", html: '<div class="loader-002"><span></span><span></span><span></span></div>', category: "dots" },
  { id: "003", name: "Morphing Blob", html: '<div class="loader-003"></div>', category: "shapes" },
  { id: "004", name: "Wave Bars", html: '<div class="loader-004"><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "005", name: "Dual Ring", html: '<div class="loader-005"></div>', category: "spinners" },
  { id: "006", name: "Pulsing Ripple", html: '<div class="loader-006"><span></span><span></span></div>', category: "pulses" },
  { id: "007", name: "Gradient Spinner", html: '<div class="loader-007"></div>', category: "spinners" },
  { id: "008", name: "Folding Cube", html: '<div class="loader-008"><span></span><span></span><span></span><span></span></div>', category: "3d" },
  { id: "009", name: "Hexagon Pulse", html: '<div class="loader-009"></div>', category: "shapes" },
  { id: "010", name: "Matrix Grid", html: '<div class="loader-010"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "grids" },
  { id: "011", name: "Triangle Spin", html: '<div class="loader-011"></div>', category: "shapes" },
  { id: "012", name: "Elastic Ball", html: '<div class="loader-012"></div>', category: "bouncing" },
  { id: "013", name: "Neon Circle", html: '<div class="loader-013"></div>', category: "glowing" },
  { id: "014", name: "Hourglass Flip", html: '<div class="loader-014"></div>', category: "creative" },
  { id: "015", name: "Heartbeat", html: '<div class="loader-015"></div>', category: "creative" },
  { id: "016", name: "Sound Equalizer", html: '<div class="loader-016"><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "017", name: "Ping Pong Ball", html: '<div class="loader-017"></div>', category: "bouncing" },
  { id: "018", name: "Pacman Chomp", html: '<div class="loader-018"></div>', category: "creative" },
  { id: "019", name: "Planet Orbit", html: '<div class="loader-019"></div>', category: "orbits" },
  { id: "020", name: "Chat Typing", html: '<div class="loader-020"><span></span><span></span><span></span></div>', category: "dots" },
  { id: "021", name: "Rising Sun", html: '<div class="loader-021"></div>', category: "creative" },
  { id: "022", name: "Gear Cog", html: '<div class="loader-022"></div>', category: "mechanical" },
  { id: "023", name: "Radar Sweep", html: '<div class="loader-023"></div>', category: "spinners" },
  { id: "024", name: "Comet Trail", html: '<div class="loader-024"></div>', category: "orbits" },
  { id: "025", name: "Galaxy Swirl", html: '<div class="loader-025"><span></span><span></span><span></span></div>', category: "orbits" },
  // 026-050
  { id: "026", name: "Dual Planet", html: '<div class="loader-026"></div>', category: "orbits" },
  { id: "027", name: "Cog Wheel", html: '<div class="loader-027"></div>', category: "mechanical" },
  { id: "028", name: "Fire Flame", html: '<div class="loader-028"><span></span><span></span><span></span></div>', category: "creative" },
  { id: "029", name: "Lightning Bolt", html: '<div class="loader-029"></div>', category: "creative" },
  { id: "030", name: "Audio Wave", html: '<div class="loader-030"><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "031", name: "Hungry Ghost", html: '<div class="loader-031"></div>', category: "creative" },
  { id: "032", name: "Sand Timer", html: '<div class="loader-032"></div>', category: "creative" },
  { id: "033", name: "Messenger Dots", html: '<div class="loader-033"><span></span><span></span><span></span></div>', category: "dots" },
  { id: "034", name: "Pulsing Heart", html: '<div class="loader-034"></div>', category: "pulses" },
  { id: "035", name: "Blinking Eye", html: '<div class="loader-035"></div>', category: "creative" },
  { id: "036", name: "Nested Squares", html: '<div class="loader-036"><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "037", name: "Shooting Star", html: '<div class="loader-037"></div>', category: "orbits" },
  { id: "038", name: "WiFi Signal", html: '<div class="loader-038"><span></span><span></span><span></span></div>', category: "pulses" },
  { id: "039", name: "DNA Strand", html: '<div class="loader-039"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "creative" },
  { id: "040", name: "Arc Spinner", html: '<div class="loader-040"></div>', category: "spinners" },
  { id: "041", name: "Gold Coins", html: '<div class="loader-041"><span></span><span></span><span></span><span></span></div>', category: "creative" },
  { id: "042", name: "Nested Hexagons", html: '<div class="loader-042"><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "043", name: "Squash Ring", html: '<div class="loader-043"></div>', category: "bouncing" },
  { id: "044", name: "Orbit Dots", html: '<div class="loader-044"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "orbits" },
  { id: "045", name: "Glowing Bars", html: '<div class="loader-045"><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "046", name: "Newton Cradle", html: '<div class="loader-046"><span></span><span></span><span></span><span></span><span></span></div>', category: "mechanical" },
  { id: "047", name: "Shape Morph", html: '<div class="loader-047"></div>', category: "shapes" },
  { id: "048", name: "Particle Burst", html: '<div class="loader-048"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "pulses" },
  { id: "049", name: "Card Flip", html: '<div class="loader-049"><span></span><span></span><span></span></div>', category: "3d" },
  { id: "050", name: "Liquid Fill", html: '<div class="loader-050"></div>', category: "progress" },
  // 051-075
  { id: "051", name: "Diamond Spin", html: '<div class="loader-051"></div>', category: "shapes" },
  { id: "052", name: "Electron Orbit", html: '<div class="loader-052"></div>', category: "orbits" },
  { id: "053", name: "Stretch Bar", html: '<div class="loader-053"></div>', category: "bars" },
  { id: "054", name: "Flower Petals", html: '<div class="loader-054"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "creative" },
  { id: "055", name: "Diamond Grid", html: '<div class="loader-055"><span></span><span></span><span></span><span></span></div>', category: "grids" },
  { id: "056", name: "Line Bounce", html: '<div class="loader-056"></div>', category: "bouncing" },
  { id: "057", name: "Spiral Ring", html: '<div class="loader-057"></div>', category: "spinners" },
  { id: "058", name: "Coin Flip", html: '<div class="loader-058"></div>', category: "3d" },
  { id: "059", name: "Cascade Circles", html: '<div class="loader-059"><span></span><span></span><span></span></div>', category: "dots" },
  { id: "060", name: "Cross Spinner", html: '<div class="loader-060"></div>', category: "spinners" },
  { id: "061", name: "Float Squares", html: '<div class="loader-061"><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "062", name: "Gradient Wave", html: '<div class="loader-062"></div>', category: "progress" },
  { id: "063", name: "Star Pulse", html: '<div class="loader-063"></div>', category: "pulses" },
  { id: "064", name: "Triple Ring", html: '<div class="loader-064"><span></span><span></span><span></span></div>', category: "spinners" },
  { id: "065", name: "Dot Snake", html: '<div class="loader-065"><span></span><span></span><span></span><span></span><span></span></div>', category: "dots" },
  { id: "066", name: "Half Arc", html: '<div class="loader-066"></div>', category: "spinners" },
  { id: "067", name: "Cube Matrix", html: '<div class="loader-067"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "grids" },
  { id: "068", name: "Moon Orbit", html: '<div class="loader-068"><span></span><span></span></div>', category: "orbits" },
  { id: "069", name: "Dashed Ring", html: '<div class="loader-069"></div>', category: "spinners" },
  { id: "070", name: "Slider Ball", html: '<div class="loader-070"></div>', category: "bouncing" },
  { id: "071", name: "3D Card Flip", html: '<div class="loader-071"><span></span></div>', category: "3d" },
  { id: "072", name: "Breathing Orb", html: '<div class="loader-072"></div>', category: "pulses" },
  { id: "073", name: "Chase Squares", html: '<div class="loader-073"><span></span><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "074", name: "Horizon Sun", html: '<div class="loader-074"></div>', category: "creative" },
  { id: "075", name: "Segment Spin", html: '<div class="loader-075"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "spinners" },
  // 076-100
  { id: "076", name: "Dotted Ring", html: '<div class="loader-076"></div>', category: "spinners" },
  { id: "077", name: "Pendulum Swing", html: '<div class="loader-077"></div>', category: "mechanical" },
  { id: "078", name: "Grow Bars", html: '<div class="loader-078"><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "079", name: "Hex Rotate", html: '<div class="loader-079"></div>', category: "shapes" },
  { id: "080", name: "Bounce Ball", html: '<div class="loader-080"></div>', category: "bouncing" },
  { id: "081", name: "Wave Dots", html: '<div class="loader-081"><span></span><span></span><span></span><span></span><span></span></div>', category: "dots" },
  { id: "082", name: "Text Loading", html: '<div class="loader-082">Loading</div>', category: "text" },
  { id: "083", name: "Scissor Cut", html: '<div class="loader-083"></div>', category: "creative" },
  { id: "084", name: "Helix Bars", html: '<div class="loader-084"><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "085", name: "Sonar Ping", html: '<div class="loader-085"></div>', category: "pulses" },
  { id: "086", name: "Orbit Glow", html: '<div class="loader-086"></div>', category: "orbits" },
  { id: "087", name: "Gradient Blob", html: '<div class="loader-087"></div>', category: "shapes" },
  { id: "088", name: "Triple Bounce", html: '<div class="loader-088"><span></span><span></span><span></span></div>', category: "bouncing" },
  { id: "089", name: "Quad Dots", html: '<div class="loader-089"><span></span><span></span><span></span><span></span></div>', category: "dots" },
  { id: "090", name: "Pulse Bars", html: '<div class="loader-090"><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "091", name: "Plus Rotate", html: '<div class="loader-091"></div>', category: "spinners" },
  { id: "092", name: "Circle Chase", html: '<div class="loader-092"><span></span><span></span><span></span></div>', category: "spinners" },
  { id: "093", name: "Progress Slide", html: '<div class="loader-093"></div>', category: "progress" },
  { id: "094", name: "Flip Squares", html: '<div class="loader-094"><span></span><span></span><span></span></div>', category: "3d" },
  { id: "095", name: "Neon Glow Ring", html: '<div class="loader-095"></div>', category: "glowing" },
  { id: "096", name: "Dual Gears", html: '<div class="loader-096"></div>', category: "mechanical" },
  { id: "097", name: "Meteor Spin", html: '<div class="loader-097"></div>', category: "orbits" },
  { id: "098", name: "Binary Grid", html: '<div class="loader-098"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "grids" },
  { id: "099", name: "Oscillate Bars", html: '<div class="loader-099"><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "100", name: "Galaxy Core", html: '<div class="loader-100"><span></span><span></span><span></span></div>', category: "orbits" },
  // 101-125 (Unique Objects)
  { id: "101", name: "Typewriter", html: '<div class="loader-101"></div>', category: "text" },
  { id: "102", name: "Paper Plane", html: '<div class="loader-102"></div>', category: "creative" },
  { id: "103", name: "Fingerprint", html: '<div class="loader-103"><span></span><span></span><span></span></div>', category: "creative" },
  { id: "104", name: "Pendulum Clock", html: '<div class="loader-104"></div>', category: "mechanical" },
  { id: "105", name: "Scissors", html: '<div class="loader-105"></div>', category: "creative" },
  { id: "106", name: "Washing Machine", html: '<div class="loader-106"></div>', category: "mechanical" },
  { id: "107", name: "Heart Monitor", html: '<div class="loader-107"></div>', category: "creative" },
  { id: "108", name: "Percentage", html: '<div class="loader-108">%</div>', category: "text" },
  { id: "109", name: "Bouncing Letters", html: '<div class="loader-109"><span>L</span><span>O</span><span>A</span><span>D</span><span>I</span><span>N</span><span>G</span></div>', category: "text" },
  { id: "110", name: "Pie Chart", html: '<div class="loader-110"></div>', category: "progress" },
  { id: "111", name: "Coffee Cup", html: '<div class="loader-111"></div>', category: "creative" },
  { id: "112", name: "Sandglass 3D", html: '<div class="loader-112"></div>', category: "3d" },
  { id: "113", name: "Cassette Tape", html: '<div class="loader-113"></div>', category: "creative" },
  { id: "114", name: "Vinyl Record", html: '<div class="loader-114"></div>', category: "creative" },
  { id: "115", name: "TV Static", html: '<div class="loader-115"></div>', category: "creative" },
  { id: "116", name: "Compass", html: '<div class="loader-116"></div>', category: "mechanical" },
  { id: "117", name: "Fan Blades", html: '<div class="loader-117"><span></span><span></span><span></span></div>', category: "mechanical" },
  { id: "118", name: "Stopwatch", html: '<div class="loader-118"></div>', category: "mechanical" },
  { id: "119", name: "Metronome", html: '<div class="loader-119"></div>', category: "mechanical" },
  { id: "120", name: "Newton Balls", html: '<div class="loader-120"><span></span><span></span><span></span><span></span><span></span></div>', category: "mechanical" },
  { id: "121", name: "Slot Machine", html: '<div class="loader-121"><span></span><span></span><span></span></div>', category: "creative" },
  { id: "122", name: "Dice Roll", html: '<div class="loader-122"></div>', category: "3d" },
  { id: "123", name: "Hourglass Sand", html: '<div class="loader-123"></div>', category: "creative" },
  { id: "124", name: "Lighthouse", html: '<div class="loader-124"></div>', category: "creative" },
  { id: "125", name: "Blinking Cursor", html: '<div class="loader-125"></div>', category: "text" },
  // 126-150 (More Unique Designs)
  { id: "126", name: "Spinning Rings", html: '<div class="loader-126"><span></span><span></span><span></span></div>', category: "spinners" },
  { id: "127", name: "Gauge Meter", html: '<div class="loader-127"></div>', category: "mechanical" },
  { id: "128", name: "Fading Squares", html: '<div class="loader-128"><span></span><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "129", name: "Circular Progress", html: '<div class="loader-129"></div>', category: "progress" },
  { id: "130", name: "Wobble", html: '<div class="loader-130"></div>', category: "bouncing" },
  { id: "131", name: "Typewriter Dots", html: '<div class="loader-131"></div>', category: "text" },
  { id: "132", name: "Shaking Box", html: '<div class="loader-132"></div>', category: "bouncing" },
  { id: "133", name: "Growing Circle", html: '<div class="loader-133"></div>', category: "pulses" },
  { id: "134", name: "DNA Ladder", html: '<div class="loader-134"><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "creative" },
  { id: "135", name: "Jumping Ball", html: '<div class="loader-135"></div>', category: "bouncing" },
  { id: "136", name: "Flip Card", html: '<div class="loader-136"></div>', category: "3d" },
  { id: "137", name: "Pulse Ring", html: '<div class="loader-137"></div>', category: "pulses" },
  { id: "138", name: "Loading Text", html: '<div class="loader-138"></div>', category: "text" },
  { id: "139", name: "Spinning Diamond", html: '<div class="loader-139"></div>', category: "shapes" },
  { id: "140", name: "Bouncing Bars", html: '<div class="loader-140"><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "141", name: "Rotating Square", html: '<div class="loader-141"></div>', category: "shapes" },
  { id: "142", name: "Circular Dots", html: '<div class="loader-142"><span></span><span></span><span></span><span></span></div>', category: "dots" },
  { id: "143", name: "Blinking Grid", html: '<div class="loader-143"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "grids" },
  { id: "144", name: "Ripple", html: '<div class="loader-144"><span></span><span></span></div>', category: "pulses" },
  { id: "145", name: "Glowing Dot", html: '<div class="loader-145"></div>', category: "glowing" },
  { id: "146", name: "Sliding Blocks", html: '<div class="loader-146"><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "147", name: "Morphing Shape", html: '<div class="loader-147"></div>', category: "shapes" },
  { id: "148", name: "Loading Circle", html: '<div class="loader-148"></div>', category: "spinners" },
  { id: "149", name: "Wave Line", html: '<div class="loader-149"><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "150", name: "Spinning Coin", html: '<div class="loader-150"></div>', category: "3d" },
  // 151-175 (Even More Unique Designs)
  { id: "151", name: "Rotating Dots", html: '<div class="loader-151"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>', category: "dots" },
  { id: "152", name: "Infinity Loop", html: '<div class="loader-152"></div>', category: "orbits" },
  { id: "153", name: "Stacked Layers", html: '<div class="loader-153"><span></span><span></span><span></span></div>', category: "spinners" },
  { id: "154", name: "Pulsing Squares", html: '<div class="loader-154"><span></span><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "155", name: "Zig Zag", html: '<div class="loader-155"></div>', category: "bouncing" },
  { id: "156", name: "Orbit Planet", html: '<div class="loader-156"></div>', category: "orbits" },
  { id: "157", name: "Elastic Line", html: '<div class="loader-157"></div>', category: "progress" },
  { id: "158", name: "Clock Hands", html: '<div class="loader-158"></div>', category: "mechanical" },
  { id: "159", name: "Bouncing Line", html: '<div class="loader-159"></div>', category: "bouncing" },
  { id: "160", name: "Spinning Arcs", html: '<div class="loader-160"></div>', category: "spinners" },
  { id: "161", name: "Scale Dots", html: '<div class="loader-161"><span></span><span></span><span></span><span></span></div>', category: "dots" },
  { id: "162", name: "Folding Square", html: '<div class="loader-162"></div>', category: "3d" },
  { id: "163", name: "Radar Scan", html: '<div class="loader-163"></div>', category: "spinners" },
  { id: "164", name: "Expanding Ring", html: '<div class="loader-164"></div>', category: "pulses" },
  { id: "165", name: "Slide Bars", html: '<div class="loader-165"><span></span><span></span><span></span><span></span><span></span></div>', category: "bars" },
  { id: "166", name: "Rotating Hexagon", html: '<div class="loader-166"></div>', category: "shapes" },
  { id: "167", name: "Dot Trail", html: '<div class="loader-167"><span></span><span></span><span></span></div>', category: "dots" },
  { id: "168", name: "Flip Dots", html: '<div class="loader-168"><span></span><span></span><span></span></div>', category: "3d" },
  { id: "169", name: "Square Wave", html: '<div class="loader-169"><span></span><span></span><span></span><span></span></div>', category: "shapes" },
  { id: "170", name: "Spinner Dots", html: '<div class="loader-170"></div>', category: "dots" },
  { id: "171", name: "Rolling Ball", html: '<div class="loader-171"></div>', category: "bouncing" },
  { id: "172", name: "Glitch Box", html: '<div class="loader-172"></div>', category: "creative" },
  { id: "173", name: "Orbit Ring", html: '<div class="loader-173"></div>', category: "orbits" },
  { id: "174", name: "Breathing Square", html: '<div class="loader-174"></div>', category: "pulses" },
  { id: "175", name: "Triple Spinner", html: '<div class="loader-175"><span></span><span></span><span></span></div>', category: "spinners" },
];

// Category definitions
export const categories = [
  { id: "all", name: "All", icon: "✦" },
  { id: "spinners", name: "Spinners", icon: "◌" },
  { id: "dots", name: "Dots", icon: "•••" },
  { id: "bars", name: "Bars", icon: "▮▮▮" },
  { id: "shapes", name: "Shapes", icon: "◇" },
  { id: "pulses", name: "Pulses", icon: "◎" },
  { id: "orbits", name: "Orbits", icon: "◯" },
  { id: "bouncing", name: "Bouncing", icon: "⬤" },
  { id: "grids", name: "Grids", icon: "▦" },
  { id: "3d", name: "3D", icon: "◰" },
  { id: "glowing", name: "Glowing", icon: "✧" },
  { id: "mechanical", name: "Mechanical", icon: "⚙" },
  { id: "creative", name: "Creative", icon: "★" },
  { id: "progress", name: "Progress", icon: "▬" },
  { id: "text", name: "Text", icon: "Aa" },
];